apiVersion: apps/v1
kind: Deployment
metadata:
  name: myrest-deployment
  labels:
    app: myrest
    monitored-by: prometheus
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myrest
  template:
    metadata:
      labels:
        app: myrest
        monitored-by: prometheus
    spec:
      containers:
        - name: myrest
          image: docker-registry.devops.gupshup.me/gsdevops/nonrest
          ports:
            - name: web
              containerPort: 8080
          resources:
            limits:
              cpu: 2
            requests:
              cpu: 2
---
apiVersion: v1
kind: Service
metadata:
  name: myrest-service
  labels:
    app: myrest
    monitored-by: prometheus
spec:
  selector:
    app: myrest
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: myrest
  labels:
    monitored-by: prometheus
spec:
  selector:
    matchLabels:
      monitored-by: prometheus
  endpoints:
    - port: web
      path: /actuator/prometheus
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
 name: myrest
 labels:
   monitored-by: prometheus
spec:
 selector:
   matchLabels:
     app: myrest
 podMetricsEndpoints:
   - port: web
     path: /actuator/prometheus
#---
#apiVersion: autoscaling/v1
#kind: HorizontalPodAutoscaler
#metadata:
#  name: myrest-hpa
#spec:
#  maxReplicas: 10
#  minReplicas: 1
#  scaleTargetRef:
#    apiVersion: apps/v1
#    kind: Deployment
#    name: myrest-deployment
#  targetCPUUtilizationPercentage: 50
